Add priority parameter for website
adespresso/WhiteLabelBundle pull request #2
Opened 2017-11-14 17:54 UTC by andreaposadino

Can be an idea to add a priority parameter for website to handle websites order

2017-11-17 13:43 UTC, mbiagetti commented
after squash the fixup! remember to reword the commit 1dd41bf (`Add PriorityValueAlreadyUsedException` instead of `Add PriorityValueAlreadyUsedExceptionException`)

2017-11-17 15:10 UTC, EmanueleMinotto commented on composer.json
> +  "version": "1.1.0",
https://getcomposer.org/doc/04-schema.md#version
> Optional if the package repository can infer the version from somewhere, such as the VCS tag name in the VCS repository. In that case it is also recommended to omit it.

2017-11-17 16:56 UTC, mbiagetti commented
After merge create a new tags/release, please

2017-11-21 09:38 UTC, daBarbe requested changes
Just a couple of changes for you.

2017-11-21 09:38 UTC, daBarbe commented on DependencyInjection/AeWhiteLabelExtension.php
> +            );
You could modify the constructor so you don't have to specify the message here.

2017-11-21 09:38 UTC, daBarbe commented on Tests/DependencyInjection/AeWhiteLabelExtensionTest.php
> +    }
Change this test to remove the real names (but do not delete it).

2017-11-21 15:59 UTC, daBarbe approved these changes

2017-11-21 15:59 UTC, daBarbe commented
LGTM :+1:

Squash the fixups, rebase, and 🚢  !

#approved

2017-11-21 16:21 UTC, merged